### ISSUE TITLE
 ./util/OneHot.lua:17: attempt to call method 'long' (a nil value)

### ISSUE THREAD

**Issue by cemoody** [karpathy/char-rnn#29]
Running with the GPU:

`th train.lua -data_dir data/stylist_notes_01 -rnn_size 512 -num_layers 3 -gpuid 1`

On an EC2 GPU machine gets me this error:

```
ubuntu@ip-10-0-0-99:~/torch/build/char-rnn$ th train.lua -data_dir data/stylist_notes_01 -rnn_size 512 -num_layers 3 -gpuid 1
using CUDA on GPU 1...
loading data files...
cutting off end of data so that the batches/sequences divide evenly
reshaping tensor...
data load done. Number of batches in train: 332442, val: 17496, test: 1
vocab size: 147
creating an LSTM with 3 layers
number of parameters in the model: 5631635
cloning criterion
cloning rnn
/home/ubuntu/torch-distro/install/bin/luajit: ./util/OneHot.lua:17: attempt to call method 'long' (a nil value)
stack traceback:
        ./util/OneHot.lua:17: in function 'func'
        ...u/torch-distro/install/share/lua/5.1/nngraph/gmodule.lua:214: in function 'neteval'
        ...u/torch-distro/install/share/lua/5.1/nngraph/gmodule.lua:244: in function 'forward'
        train.lua:173: in function 'opfunc'
        ...ntu/torch-distro/install/share/lua/5.1/optim/rmsprop.lua:32: in function 'rmsprop'
        train.lua:216: in main chunk
        [C]: in function 'dofile'
        ...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00406170
```

However, turning off the GPU and running in just CPU mode works great! I've been diving into this, but can't see the issue. Any help would be greatly appreciated!

**Comment by cemoody** [comment]
For anyone else having this issue, it appears to be confined to multi-GPU instances. I started an EC2 instance with a single GPU and it's all gravy now :)

**Comment by soumith** [comment]
@cemoody it's actually the cutorch version. If you updated to the latest version (or installed torch from scratch), you wouldn't see this error.

This bug was fixed in this commit on March 30th: https://github.com/torch/cutorch/commit/41006b8b96c7b91ac7175b60322b2c61b3e2af9d

**Comment by cemoody** [comment]
@soumith  Perfect, thanks!

**Comment by Spandan-Madan** [comment]
I upgraded cutorch but am still getting this error. Anyone got any advice? Though the model I'm loading is not for charnn, it's a custom model. However, this the only relevant link that pops up when I search for the error. Here's the error trace: 

```
[string "model_lineback = model_lineback:float()"]:1: attempt to call method 'float' (a nil value)
stack traceback:
        [string "model_lineback = model_lineback:float()"]:1: in main chunk
        [C]: in function 'xpcall'
        /home/t-spmada/torch/install/share/lua/5.1/trepl/init.lua:679: in function 'repl'
        ...mada/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
        [C]: at 0x00405d50
```
